# uname.yml
---
- hosts: webservers:loadbalancers
  gather_facts: false
  tasks:
    - name: Get OS type
      shell: uname -a
      register: uname_output

    - name: Display OS type
      debug:
        var: uname_output.stdout
