# yum-update.yml

---
  - hosts: webservers:loadbalancers
    become: true
    tasks:
      - name: Updating yum packages
        yum: name=* state=latest
        #or
        # yum:
        #   name: '*'
        #   state: latest